### ISSUE TITLE
Personal Decks not imported

### ISSUE THREAD

**Issue by Soniic15** [jceddy/DailyArenaDeckAdvisor#116]
Hi!

I'm having trouble with seeing anything else except for the "Meta Report" slide on the left side of the menu. I've checked the "common issues" part in the mtgarena zone and when looking for the "PlayerInventory.GetPlayerCardsV3" text in the outpug_log.txt file I don't see the list of key/value pairs matching Arena card Ids to quantities in my inventory that I'm supposed to see. 
I've verified that the “Detailed Logs(Plugin Support)” setting is checked but still not working. 

The strange thing is that when I click in any deck of the "Meta Report", the app knows which cards I'm missing and which not. So the problem is in importing my existing decks and seeing my personal decks I guess.

Any idea for solving this issue?

Thank you!

**Comment by jceddy** [comment]
It will only show decks from your inventory that you are missing cards from. If you only have completed decks in the inventory, they won't show up...is that what you're seeing, maybe?

**Comment by ketsa** [comment]
I have 16 decks with missing cards, only 6 are shown in DADA.

**Comment by jceddy** [comment]
There are various reasons why a deck might not show up in DADA...if you included a card that it doesn't know about, have an illegal deck, etc. Also, decks show up under the category(ies) that they fit in. Can you change the format filter and see if they show up under a different format?

If you are pretty sure none of these are the issue, can you attach your output_log.txt and DADA log files here so I can take a look?
