### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by Magodcs** [jceddy/DailyArenaDeckAdvisor#117]
After updating DailyArena all the interface is in spanish (My system language) i would like it to be in english as used to be. 
I tried changing the config file to culture="en" (is what i understood i should do from the blog post) but didn't work.
I also deleted the "es" folder and it kinda worked, the interface was in english but the cards where still in spanish.

thanks.

**Comment by jceddy** [comment]
Try changing it to en-US in the config file.

**Comment by Magodcs** [comment]
didn't work. 
Checked the es and ru-RU folders and there is this file
Xceed.Wpf.AvalonDock.resources
That is not in the en folder, not sure if also should be one there.

**Comment by jceddy** [comment]
Can you attach your config file here, or copy/paste the text from it?

**Comment by Magodcs** [comment]
[DailyArenaDeckAdvisor.exe.zip](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4027165/DailyArenaDeckAdvisor.exe.zip)

**Comment by jceddy** [comment]
You need to un-comment the setting, as well:

Change

`<!--<add key="UICulture" value="en-US" />-->`

to

`<add key="UICulture" value="en-US" />`

**Comment by Magodcs** [comment]
Thanks!
Didn't notice it was commented. Working properly now.

**Comment by jceddy** [comment]
Good to hear.
