### ISSUE TITLE
Unhandled Exception when changing to Arena Standard and Brawl Format

### ISSUE THREAD

**Issue by AscaL** [jceddy/DailyArenaDeckAdvisor#128]
Hello, when changing the tab to "Arena Standard" i get the following screen. The same happens for "Brawl"
![image](https://user-images.githubusercontent.com/8880943/72682865-223a2300-3ad2-11ea-8db8-0fc33be77b64.png)
![image](https://user-images.githubusercontent.com/8880943/72682870-2f571200-3ad2-11ea-8ffe-7db353f027db.png)
[log2020011915.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4082774/log2020011915.txt)
[firstChanceExceptions2020011915.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4082775/firstChanceExceptions2020011915.txt)

I've also attached the logs.

Thanks for this tool is really nice! Cheers

**Comment by jceddy** [comment]
I have a fix for this but wasn't able to get it online on Friday. I don't know if I'll get a chance today, but it will be up by Monday.

I'll run additional tests against logs that have been submitted since then to verify that it fixes everyone's issues.

**Comment by jceddy** [comment]
I just put up version 1.0.6.8...can you verify whether it fixes your issue?

**Comment by AscaL** [comment]
Works for me, thanks!!
