### ISSUE TITLE
Theros cards missing

### ISSUE THREAD

**Issue by realJohnDoe** [jceddy/DailyArenaDeckAdvisor#146]
I was wondering when some Theros Decks show up in the Deck Advisor. On MtgGoldfish there are already quite a lot. Am I missing something?

**Comment by jceddy** [comment]
The source that the app gets the card database from hasn't updated it with thb, I'm working on switching to another source.

**Comment by jceddy** [comment]
Unfortunately I also lost a hard drive today and it's taking all day to restore from backup. This might only require a back-end server change, though, so hopefully I can have something soon.

**Comment by jceddy** [comment]
Okay, it should be getting THB cards and showing THB decks now.

**Comment by realJohnDoe** [comment]
Amazing, thanks for this superquick response!

**Comment by realJohnDoe** [comment]
One more question. How do you select, which decks from mtggoldfish to show?

**Comment by jceddy** [comment]
It just shows all the decks it grabbed from the main decks pages for the format, as well as any imported decks with missing cards from your library.

**Comment by realJohnDoe** [comment]
I still dont get it. This page?
https://www.mtggoldfish.com/metagame/arena_standard/full#paper

I find a lot more decks on mtggoldfish than in the app and some of the Decks in the App, I cannot find on mtggoldfish. For example one RG aggro with 1 Gallia of the Endless Dance and 2 Klothys.

**Comment by jceddy** [comment]
It only uses mtggoldfish for Standard and Brawl decks, the Arena Standard decks come from MTG Arena Pro. The mtggoldfish section for arena standard was horrible when the tool was originally created. If it's better now, I may consider pulling that deck data in again.

**Comment by realJohnDoe** [comment]
Ah, I see.
Yeah, the Arena section on mtggoldfish is pretty scarce.
