### ISSUE TITLE
v1.0.2.9 - Rotation Proof - Boros Battalion has Luminous Bonds

### ISSUE THREAD

**Issue by ghost** [jceddy/DailyArenaDeckAdvisor#16]
Noticed today that Boros Battalion with Rotation Proof select has 3 Luminous Bonds with !! next to them stating they are rotating out on 10/2019

![Screenshot_083019_094013_AM](https://user-images.githubusercontent.com/13244707/64025309-68362080-cb0a-11e9-9e2f-935510762d19.jpg)

**Comment by jceddy** [comment]
Ah, that's because rivals is rotating out and guilds of Ravnica also has luminous bonds. Minor bug, will fix.

**Comment by ghost** [comment]
RR - also updated the wiki to the new version

**Comment by jceddy** [comment]
Fixed by commit: https://github.com/jceddy/DailyArenaDeckAdvisor/commit/5cf68698b1042389b8be84e2a27d6212953a3ccb
