### ISSUE TITLE
Unhandled Exception while Loading Card Base

### ISSUE THREAD

**Issue by tharec79** [jceddy/DailyArenaDeckAdvisor#166]
Unfortunately the programm always crashes on me (see attached logs
[log2020031419.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4333209/log2020031419.txt)
[firstChanceExceptions2020031419.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4333210/firstChanceExceptions2020031419.txt)

)
I already changed the language of the system from German to English, but that did not help. Any suggestions?

**Comment by jceddy** [comment]
I found a bug due to a change in the external card database library the application uses that is causing this. I am currently testing a change that should be available later today in version 1.0.7.4.

**Comment by jceddy** [comment]
I just pushed version 1.0.7.4. Can you check verify whether the update fixes your issue?

**Comment by tharec79** [comment]
Thanks for the fast response. Works like a charm now :-)
