### ISSUE TITLE
Unhandled Exception - sending data to server

### ISSUE THREAD

**Issue by Foilface** [jceddy/DailyArenaDeckAdvisor#168]
[output_log.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4333264/output_log.txt)

Throws this error after it attempts to load card database.
Thanks for any guidance.

**Comment by Bigwookiemike** [comment]
I also have this problem.
[log2020031517.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4335308/log2020031517.txt)
[firstChanceExceptions2020031516.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4335309/firstChanceExceptions2020031516.txt)
[firstChanceExceptions2020031517.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4335310/firstChanceExceptions2020031517.txt)
[log2020031510.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4335311/log2020031510.txt)
[log2020031516.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4335312/log2020031516.txt)

**Comment by jceddy** [comment]
I found a bug due to a change in the external card database library the application uses that is causing this. I am currently testing a change that should be available later today in version 1.0.7.4.

**Comment by jceddy** [comment]
Closing as replica of #166
