### ISSUE TITLE
Unhandled exception at start up

### ISSUE THREAD

**Issue by JDstl99** [jceddy/DailyArenaDeckAdvisor#169]
It freezes every time I start it up saying, "Unhandled Exception - Sending Data to Server"

[firstChanceExceptions2020031415.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4333418/firstChanceExceptions2020031415.txt)
[firstChanceExceptions2020031416.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4333419/firstChanceExceptions2020031416.txt)
[log2020031415.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4333420/log2020031415.txt)
[log2020031416.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4333421/log2020031416.txt)

**Comment by jceddy** [comment]
I found a bug due to a change in the external card database library the application uses that is causing this. I am currently testing a change that should be available later today in version 1.0.7.4.

**Comment by jceddy** [comment]
Closing as replica of #166
