### ISSUE TITLE
Unhandled Exception on startup

### ISSUE THREAD

**Issue by 0539143** [jceddy/DailyArenaDeckAdvisor#170]
I tried out all of the suggested fixes such as deleting the .json files and changing the config graphics settings first. The error looks like some kind of incorrect grabbing of something, so nothing else I could think of to do was relevant.

Here are the logs on the errors I'm getting:
[log2020031600.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4336076/log2020031600.txt)
[firstChanceExceptions2020031600.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4336077/firstChanceExceptions2020031600.txt)

**Comment by jceddy** [comment]
I found a bug due to a change in the external card database library the application uses that is causing this. I am currently testing a change that should be available later today in version 1.0.7.4.

**Comment by jceddy** [comment]
Closing as replica of #166
