### ISSUE TITLE
Unable to stop it from crashing on Win 10

### ISSUE THREAD

**Issue by cannondt** [jceddy/DailyArenaDeckAdvisor#173]
Hi,
Every time I run the app, it either crashes soon after opening or after a few minutes, either way I am unable to use this. I tried the options outlined at mtga zone to no avail (including the bitmap scaling config change). I am attaching the logs from the AppData folder of DailyArena. Version is the latest, 1.0.7.4 

Please help if possible.

Ananth

[firstChanceExceptions2020032003.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4357099/firstChanceExceptions2020032003.txt)
[log2020032003.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4357100/log2020032003.txt)

**Comment by jceddy** [comment]
I'm in here today looking at the latest issues, will update as I am able.

**Comment by jceddy** [comment]
I fixed a server-side issue to the MTGArena.pro making a change on their site. Can you give it a try again?

I'll look at your logs in the meantime.

**Comment by jceddy** [comment]
Also, can you attach the output_log.txt file from C:\Users\YOUR USER\AppData\LocalLow\Wizards of the Coast\MTGA ?

**Comment by cannondt** [comment]
I am sorry but I never got any message of your responses. I only got a notification today about the closure, my apologies for not providing the required information :(
