### ISSUE TITLE
Stuck loading card database

### ISSUE THREAD

**Issue by bennodxb** [jceddy/DailyArenaDeckAdvisor#19]
Hi,
1.0.3.1 wont load at all,. Gets stuck loading card database.
I deleted appdata. Uninstalled and reinstalled changed the bitmapscalingmode to linear.
No good.
Windows 10 x64

**Comment by jceddy** [comment]
Did you enable detailed logging in Arena?

**Comment by bennodxb** [comment]
i didnt, but now i have.  I don't see anything related in the logs. But I don't know what I'm looking for either.

**Comment by jceddy** [comment]
The detailed logging needs to be enabled in Arena in order for the Deck Advisor to work. Does it still hang after you enable detailed logging in Arena and re-open your collection screen?

**Comment by ghost** [comment]
bennodxb,

I had the same issue - steps to resolve:

- start Arena and select 'detailed logging' from 'Settings ... view account' - it's the link at the bottom of the view account page

- close Arena
- restart Arena and then fire up DailyArenaDeckAdvisor

That worked for me

**Comment by bennodxb** [comment]
Hey, 

Thanks guys.

I tried all the above. Still the same, it just sits there on Loading Card database.

**Comment by jceddy** [comment]
Can you attach the most recent log files from c:\Users\\{Your User}\AppData\DailyArena\DailyArenaDeckAdvisor\logs, or email them to me at dailyarena@dailyarena.net, I can take a look at see if anything jumps out at me.

**Comment by bennodxb** [comment]
I will send those logs when I get home from work. Thanks.

**Comment by jceddy** [comment]
I have reproduced this on my home laptop, but haven't had a chance to look into a fix yet.

Will re-post here when I have a fix.

**Comment by jceddy** [comment]
On my machine it looks like it is due player inventory information not being written to the Arena real-time log even though I have the detailed logging checkbox checked. Will spend some time verifying this, but might need to open a bug report with WotC.

Would be interesting to see if other trackers are having similar issues.

**Comment by jceddy** [comment]
I see that the Wizard's site says to restart Arena after toggling the setting, which I did not do.

So the sequence would be: turn on detailed logging, restart arena, open collection view, run DADA.

**Comment by jceddy** [comment]
I verified this worked on my laptop. Can you give it a try?

**Comment by bennodxb** [comment]
I tried the sequence and it gave me some error popup and didnt run at all so i uninstalled and reinstalled DADA and now its working again! yay. Thanks for the help.

**Comment by jceddy** [comment]
Cool. Be sure to let us know if you have issues again in the future!
