### ISSUE TITLE
Add a "get started" for developers

### ISSUE THREAD

**Issue by Lego6245** [jceddy/DailyArenaDeckAdvisor#2]
Is a nice QOL for folks to ensure their development environment is set up to build and test changes before opening PRs :)

**Comment by jceddy** [comment]
I'm setting up my home laptop to work on this now, so will take screenshots to include in a "get started" guide.

**Comment by ghost** [comment]
I can add to wiki when ready if you like - DERP - already added.

**Comment by jceddy** [comment]
I updated the "Getting Started" developer guide and added a link to it from the readme file: https://github.com/jceddy/DailyArenaDeckAdvisor/wiki/Getting-Started:-Developing-DADA

I'm going to close this issue now, but let me know if you see any issues with it or run into any details that you'd like to see added.
