### ISSUE TITLE
Unhandled Exception - Sending Data to Server (Error after update)

### ISSUE THREAD

**Issue by knocontrol** [jceddy/DailyArenaDeckAdvisor#208]
[log2020062703.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/4840114/log2020062703.txt)

**Comment by jceddy** [comment]
Can you also attach Player.log from Users\\{UserName}\AppData\LocalLow\Wizards of the Coast\MTGA

**Comment by jceddy** [comment]
BTW: The change in 1.0.8.3 needed to be done in one other location that is only hit when the Rotation-Proof toggle is turned on. I had missed this during testing and will push an update 1.0.8.4 for it later today. If you have the Rotation-Proof toggle on, then it's possible that is the issue you are running into.

**Comment by jceddy** [comment]
1.0.8.4 has been pushed now...can you verify whether it fixes your issue?

**Comment by knocontrol** [comment]
my apologies for not responding quicker but everything is working now thank
you!

**Comment by jceddy** [comment]
Thanks!
