### ISSUE TITLE
v1.0.3.3 stops at 'processing collection from log' after Eldraine update

### ISSUE THREAD

**Issue by ghost** [jceddy/DailyArenaDeckAdvisor#22]
I tried uninstalling and reinstalling DADA.

log checkbox is on in MTGA.

I can provide logs if desired.

Mark

**Comment by jceddy** [comment]
They probably broke something with the update. I won't be able to fix it until tomorrow, but I should have a fix by then.

**Comment by ghost** [comment]
I figured they changed the log file format or something.

**Comment by jceddy** [comment]
At least on issue I found was due to the way I was fetching land color data on the server side. Working on fixing that now.

**Comment by jceddy** [comment]
Thankfully scryfall has now added "historic" as a format for searching...makes my job a lot easier!

**Comment by ghost** [comment]
Excellent.  Available to test when you give me the word.

**Comment by jceddy** [comment]
It should actually work with version 1.0.3.3 now...it was only a server-side change. There was an exception due to the lands info not picking up lands like "Foul Orchard", etc.

**Comment by ghost** [comment]
Testing momentarily

**Comment by jceddy** [comment]
I am actually pushing 1.0.3.4, so you can test with that, if you like.

**Comment by jceddy** [comment]
It's pushed now...enjoy the progress bars... :P

**Comment by ghost** [comment]
works now - the progress bars are COOL

**Comment by jceddy** [comment]
😎 - Good to hear, closing the issue now. Will have updates about new functionality later today.
