### ISSUE TITLE
v1.0.3.5 Application Crashing 

### ISSUE THREAD

**Issue by jfortune0620** [jceddy/DailyArenaDeckAdvisor#23]
The application is loading properly (with my collection) but closes without an error after approximately 5 seconds.   Have tried standard troubleshooting (reinstalled, ran as admin).
[logs.zip](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3664069/logs.zip)

**Comment by jceddy** [comment]
Took a look at your logs and I don't actually see any errors (not even the "common" ones that I address in the troubleshooting guide).  
  
Is there a file called "DailyArenaDeckAdvisor.exe.config" in the application's install folder? (usually C:\Program Files\DailyArena\DailyArenaDeckAdvisor)

**Comment by jfortune0620** [comment]
Yes, that file is there.

**Comment by jfortune0620** [comment]
I may be due for a Windows rollback.  I've experienced unexpected behaviour from a couple of other programs.

**Comment by jceddy** [comment]
On thing you can try is changing your bitmap scaling in the exe.config file like this:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
	<startup>
		<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.2" />
	</startup>

	<appSettings>
		<add key="BitmapScalingMode" value="Linear" />
	</appSettings>
</configuration>
```

But I didn't see the stuff in the log that usually indicates this is your problem.

If you do try that and it works, then it likely means you have an out of date video card driver or something similar.

**Comment by jfortune0620** [comment]
Thanks.  I tried that; it did not change, still force closed after a couple of seconds.

**Comment by jceddy** [comment]
Alright. I'll try to think whether there's something else I can think of for debugging.

It seems like the program is stopping right after a background thread finishes, but I don't see any reason for it. Basically it seems like once all of my code finishes and the windows presentation stuff is left to its own devices is when it's stopping.

If you're having issues in other applications, too, though, and you just did an update I'm suspicious that your update introduced some incompatibility or something.

**Comment by jfortune0620** [comment]
Windows repair has fixed the issue.  Thanks for your time.
