### ISSUE TITLE
Suggested replacements include nonstandard cards

### ISSUE THREAD

**Issue by ChaseOfSpades** [jceddy/DailyArenaDeckAdvisor#233]
The Standard setting includes recently rotated cards.
![2](https://user-images.githubusercontent.com/21208382/95148169-aad81c80-0750-11eb-8dad-8397abd9956d.PNG)

**Comment by jceddy** [comment]
Question: Are you still seeing this? I think it might have been due to the fact that it uses the paper rotation date which is later than the Arena one.

**Comment by ChaseOfSpades** [comment]
Yes I am. Do i need to refresh anything on my end?

**Comment by jceddy** [comment]
Can you attach you log file here?

C:\Users\\{{user}}\AppData\LocalLow\Wizards Of The Coast\MTGA\Player.log

**Comment by ChaseOfSpades** [comment]
[Player.log](https://github.com/jceddy/DailyArenaDeckAdvisor/files/5433072/Player.log)

**Comment by jceddy** [comment]
I'm sorry I lost track of this one. It looks like it isn't doing this anymore now that I check it today. Please let me know if you still see this.
