### ISSUE TITLE
please help with player info

### ISSUE THREAD

**Issue by therealRJBenson** [jceddy/DailyArenaDeckAdvisor#239]
i downloaded this application but my player info is not showing. I have the 64 bit-english version. checked the log, did not see the player string code but I also dont code so im not sure. please help. [
![Capture](https://user-images.githubusercontent.com/77418269/104522110-425ccf00-55cc-11eb-8910-eb716410c6c3.JPG)
[output_log.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/5811521/output_log.txt)

](url)

**Comment by jceddy** [comment]
I'm not clear what player info you are looking for here.
