### ISSUE TITLE
Support for Localization

### ISSUE THREAD

**Issue by jceddy** [jceddy/DailyArenaDeckAdvisor#24]
Move strings out to a resource file so that I or others can easily do some localization work. (I had someone volunteer for Russian, so seems like a good time to do it).

**Comment by jceddy** [comment]
Partial support for localization was added in release 1.0.3.7, which was pushed this morning.

Russian translations for a bunch of UI elements, and all of the set names as well, have been added. Due to a bug in the updater (which is also fixed in 1.0.3.7), the UI element translations won't be included in automatic updates until version 1.0.3.8 at the earliest. The 1.0.3.7 installer .msi *does* include those, as well, so anyone who wants to start seeing Russian can re-install using the installer if they don't want to wait another week or so for the auto-update.

**Comment by jceddy** [comment]
New version 1.0.4.0 that went up today includes Russian translations for the main application in the auto-updater.

All the work for localization and Russian translation is now finished for the main program. Work still needs to be done for the updater/launcher/installer.

**Comment by jceddy** [comment]
Launcher got localization added in 1.0.4.4. Will get it in the Updater, at least, for the next "big" release.

**Comment by AndreyChilly** [comment]
Is this current version?
https://raw.githubusercontent.com/jceddy/DailyArenaDeckAdvisor/master/DailyArenaDeckAdvisor/Properties/Resources.en.resx

Can I use it to extract all the strings to separate spreadsheet?

**Comment by jceddy** [comment]
Yes.

**Comment by jceddy** [comment]
All of the localization files for the main program can also be seen here: https://github.com/jceddy/DailyArenaDeckAdvisor/tree/master/DailyArenaDeckAdvisor/Properties

They are the Resources*.resx files.

Currently there is a **.en** one for English as well as a **.ru** one for Russian, as well as a default one that is just Resources.resx that is just the exact same thing as the **.en** one.

**Comment by jceddy** [comment]
We have a few more translations added, here is what I got from Google Translate:

Error Sending Data to Server => Ошибка отправки данных на сервер
Github Issue => Github проблема
Created => созданный
Exists => Существует

The last three are used to construct messages like "Github Issue 42 Created" or "Github Issue 42 Exists". If there is some grammatical thing in Russian that requires a different ordering of these phrases, I'll have to change how the resource entries for them are handled.

**Comment by AndreyChilly** [comment]
Finally got some more spare time for translation.
In next  12 hours updated translation will be available here:
https://docs.google.com/spreadsheets/d/1XMs7rBl96sy9XBpFjvkEbgCO3ew40D89L0FbMzLufHQ/edit?usp=sharing

Dose I got it right that "Rarity_Mythic/Rare/..." used in two places:
![image](https://user-images.githubusercontent.com/56841393/67618065-a2622c80-f7f2-11e9-9039-2e29eb08449d.png)
In Filters screen and in Wilde cards needed?

**Comment by AndreyChilly** [comment]
All the strings are translated and available in Google spreadsheet (link posted above). Hope I didn't missed anything.

**Comment by jceddy** [comment]
Yes, you were correct about the rarities being used in two places. Thanks for the update!

**Comment by jceddy** [comment]
The rarities are also in the sort strings, but I embedded them in long strings. I guess I could have broken them up like I did for the filters, not sure why I didn't.

**Comment by jceddy** [comment]
I have a new field: TextBlock_EnableDetailed
This shows a message if it's detected that the player's inventory information hasn't been dumped to the Arena log file.

English is:

Please turn on detailed logging in Arena by going to Settings->View Account and checking "Detailed Logs(Plugin Support)", and browse to your collection screen before running Daily Arena Deck Advisor. You may need to restart Arena for the setting change to take effect.

Google translate gives me this for Russian:

Пожалуйста, включите подробный вход в Arena, зайдя в Настройки->Просмотр учетной записи и отметив «Подробные журналы (поддержка плагинов)», и перейдите к Сборник перед запуском Daily Arena Deck Advisor. Возможно, вам придется перезапустить Arena, чтобы изменения вступили в силу.

I'll have it checked in shortly after I merge in the other translations.

**Comment by jceddy** [comment]
Everything is merged into Github now.

**Comment by jceddy** [comment]
I've got the final major piece for localization/translation added now (the installer).

I have a (probably pretty bad) Russian translation of the EULA here (it's a WordPad rich text document):
https://github.com/jceddy/DailyArenaDeckAdvisor/raw/master/DailyArenaDeckAdvisorSetup/Eula-ru.rtf

The English version (for comparison) is here:
https://github.com/jceddy/DailyArenaDeckAdvisor/raw/master/DailyArenaDeckAdvisorSetup/Eula-en.rtf

There's also a resource file similar to the one for the main application, here:
https://raw.githubusercontent.com/jceddy/DailyArenaDeckAdvisor/master/DailyArenaDeckAdvisorSetup/Product_ru-RU.wxl

The English version is here:
https://raw.githubusercontent.com/jceddy/DailyArenaDeckAdvisor/master/DailyArenaDeckAdvisorSetup/Product_en-us.wxl

Later this week (probably around Friday), once I have other changes merged and tested, I will add a link to the Russian version of the installer, and we can consider the Russian translation part "finished", except for possible future changes to the program.

Pretty exciting...once this one is live, I will be polling to see what other languages people are interested in and looking for more translators. :)

**Comment by jceddy** [comment]
Added four more strings:

Player Decks => Колоды игроков
No Cards Needed => Карты не нужны
No Wildcards Needed => Подстановочные знаки не нужны
Replacements Required => Требуются замены

**Comment by jceddy** [comment]
I'm closing this issue, as the bulk of the localization support has been added and the only thing left for the Russian translations is for @AndreyChilly to help with some clean-up.  
  
Feel free to keep communicating on this issue after it's closed, though. I will be opening new issues for other languages as we work on adding support.

**Comment by jceddy** [comment]
I added string:

Enter Card Text Filter => Введите текстовый фильтр карты

**Comment by jceddy** [comment]
Actually, I changed it:

Enter Card Name Filter => Фильтр ввода имени карты

**Comment by jceddy** [comment]
One more: Deck Score => Счет колоды
