### ISSUE TITLE
Can't Click Deck Links

### ISSUE THREAD

**Issue by GCotts** [jceddy/DailyArenaDeckAdvisor#240]
I am unable to click the deck links in the "Top Decks To Build For Meta" section. Clicking just doesn't do anything.

**Comment by jceddy** [comment]
Can you attach your log file(s) here? I just tested and it's working fine for me.

**Comment by GCotts** [comment]
Sorry, how do I do that? Don't know where I find those.

**Comment by jceddy** [comment]
The Arena player log can be found here:

C:\Users\{{user}}\AppData\LocalLow\Wizards Of The Coast\MTGA\Player.log

The Deck Advisor log can be found here:

C:\Users\{{user}}\AppData\LocalLow\DailyArena\DailyArenaDeckAdvisor\logs

Just attach the latest one for each "log" and "firstChanceExceptions" files.

You can attach them here by dragging and dropping.

**Comment by jceddy** [comment]
BTW, I just pushed a new version today...it might be worth running it to get the update and see if it works for you now.

**Comment by GCotts** [comment]
Thanks so much. I did the latest update but there still is no effect from clicking on the deck links. I think I've attached all the logs you mentioned but let me know if I screwed something up. Thanks again.
[Player.log](https://github.com/jceddy/DailyArenaDeckAdvisor/files/5896371/Player.log)
[firstChanceExceptions2021012916.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/5896375/firstChanceExceptions2021012916.txt)
[log2021012916.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/5896377/log2021012916.txt)

**Comment by jceddy** [comment]
I just pushed version 1.0.9.0 today, can you check to see if that fixes your issue?

**Comment by GCotts** [comment]
No luck. Looks fully updated according to version #, but the links are
still unclickable for me. No meta report on the left side either, for what
it's worth.

**Comment by jceddy** [comment]
I just pushed version 1.0.9.1, but it probably won't fix anything for you.
Can I ask what version of Windows you are on, and whether your system is configured for a language other than US English?

**Comment by GCotts** [comment]
That fixed it, back in the [meta] game!
I'm using a Microsoft Surface laptop, Windows 10 Enterprise. It is a laptop
from my work (but problems were also when on my home network) so who knows
what software they may have on here that could have been messing with it.
Thanks for getting back to me about the updates.

**Comment by jceddy** [comment]
Cool, glad to hear it!
