### ISSUE TITLE
, I can't get Daily Arena Deck Advisor to show my decks any more since the latest version.

### ISSUE THREAD

**Issue by dhirasawa** [jceddy/DailyArenaDeckAdvisor#245]
Daily Arena Deck Advisor does not show my decks

https://gyazo.com/17d68635af4d365f332bee2342f04827

**Comment by jceddy** [comment]
I just pushed version 1.0.9.0, which should fix a bunch of the outstanding issues...can you verify whether it fixes yours?

**Comment by BasedAgorist** [comment]
I'm not the OP, but can confirm I'm  having a similar issue.  It doesn't show any of the decks I've imported.

**Comment by jceddy** [comment]
I just pushed version 1.0.9.1, but it wouldn't fix anything to do with showing player decks.

If you can supply your Player.log file I can take a look. One thing to note is that the advisor will only show imported decks that you don't already own all of the cards for.

**Comment by BasedAgorist** [comment]
Oh, there's definitely a couple incomplete in there.  Only recently started.  It does show my cards though, but not the incomplete decks.  Here's a link to my log.  Let me know if that doesn't work.  Wasn't sure how to upload it to the site here.

https://www.dropbox.com/s/pkmu79ol4bo7fqy/Player.log?dl=0

**Comment by jceddy** [comment]
When I load your log file, I see your player decks in the display.
![image](https://user-images.githubusercontent.com/1302263/118546428-8e0bba80-b71d-11eb-8917-63df1c4c335d.png)

**Comment by jceddy** [comment]
Is it possible you have decks from your collection hidden in Filters?

![image](https://user-images.githubusercontent.com/1302263/118546655-de831800-b71d-11eb-82da-ac34879dc0da.png)
