### ISSUE TITLE
Unhandled Exception - Sending Data to Server

### ISSUE THREAD

**Issue by Aizeru** [jceddy/DailyArenaDeckAdvisor#246]
[firstChanceExceptions2021031517.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/6140803/firstChanceExceptions2021031517.txt)
[log2021031517.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/6140804/log2021031517.txt)

**Comment by guru-of-sound** [comment]
![DeckAdvisor System Reliability Details](https://user-images.githubusercontent.com/1421548/111222697-8eb79180-85b2-11eb-9c1f-d110e690d6e7.jpg)

**Comment by jceddy** [comment]
Just wanted to update that I see the errors.

Am looking into them now...my guess is that the latest update broke something.

**Comment by jceddy** [comment]
I just pushed version 1.0.9.0, which should fix a bunch of the outstanding issues...can you verify whether it fixes yours?

**Comment by Aizeru** [comment]
i reinstalled the advisor from the Mtgazone link and checked for updates
still unhandled exception - sending data to server

**Comment by FRZZN38** [comment]
Same here, there are still some problems after the update
[firstChanceExceptions2021032511.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/6203853/firstChanceExceptions2021032511.txt)
[log2021032511.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/6203854/log2021032511.txt)

**Comment by jceddy** [comment]
Can one of you attach your Player.log file here?

**Comment by FRZZN38** [comment]
I'm not sure if this is the log you are looking for... it is located in "C:\Users\...\AppData\LocalLow\Wizards Of The Coast\MTGA"
[Player.log](https://github.com/jceddy/DailyArenaDeckAdvisor/files/6288820/Player.log)

**Comment by jceddy** [comment]
I have not been able to replicate this issue, can I ask you to try deleting all the files in this location:

C:\Users\{User}\AppData\LocalLow\DailyArena\DailyArenaDeckAdvisor

And then try running the program again?

**Comment by Aizeru** [comment]
Deleting the files in that location and restarting still provides the same
error

**Comment by jceddy** [comment]
Version 1.0.9.1 has been pushed, can you run the new version and see if it fixes your issue?

**Comment by FRZZN38** [comment]
for me it's solved with the last update, thank you!

**Comment by Aizeru** [comment]
yep the new version also fixed it for me

**Comment by gustanappo** [comment]
Hi all
Im experiencing this problem...jutst installed today!!
It worked for 1st time but suddenly came to this
Pls help

**Comment by gustanappo** [comment]
> I have not been able to replicate this issue, can I ask you to try deleting all the files in this location:
> 
> C:\Users{User}\AppData\LocalLow\DailyArena\DailyArenaDeckAdvisor
> 
> And then try running the program again?

i try to do this but app dont run....and evem reinstallingi have same issue...PLS help!

**Comment by jceddy** [comment]
I made a server-side change that may fix this without requiring a new version of the application...can folks let me know whether it is working for them now?

**Comment by jceddy** [comment]
Closing for now.
