### ISSUE TITLE
First Time Launch : Unhandled Exception - Sending Data to Server

### ISSUE THREAD

**Issue by EmirEgilli** [jceddy/DailyArenaDeckAdvisor#249]
Just downloaded the 1.0.9.0 version; followed the steps of activating logs under Account and opening the Collection after restarting the game, yet after i launch the DailyArenaDeckAdvisor i get "Unhandled Exception - Sending Data to Server"

[Player.log](https://github.com/jceddy/DailyArenaDeckAdvisor/files/6329434/Player.log)
[firstChanceExceptions2021041717.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/6329436/firstChanceExceptions2021041717.txt)
[log2021041717.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/6329437/log2021041717.txt)

**Comment by jceddy** [comment]
Version 1.0.9.1 has been pushed, can you run the new version and see if it fixes your issue?

**Comment by EmirEgilli** [comment]
Works fine now, thanks!
