### ISSUE TITLE
DailyArenaDeckAdvisor won't load correctly

### ISSUE THREAD

**Issue by kylejonmoon** [jceddy/DailyArenaDeckAdvisor#262]
I have enabled detailed logging. It was enabled long ago.  After recent MTGArena update, I verified it was still enabled.

I have restarted my computer several times; I have reinstalled Arena and DailyArenaDeckAdvisor many times.

I have navigated to my Collection and then started DailyArenaDeckAdvisor.  

It tells me to enable detailed logging.

**Comment by Image247** [comment]
I'm having the same issue.  I've turned on detailed logs within the game. Restarted, opened Collection and getting the message from DailyArenaDeckAdvisor to enable logs. I have reinstalled both Arena and DailyArenaDeckAdvisor. I go to C:\Users\{Your User}\AppData\LocalLow\Wizards of the Coast\MTGA, but I'm not finding the output_log.txt file.

**Comment by jceddy** [comment]
The name of the file changed to Player.log, I think I forgot to update the message, but the code is looking for the new name.

I will check it out.

**Comment by jceddy** [comment]
Yeah, mine is showing the same message.

**Comment by jceddy** [comment]
The Player.log file is there, and was updated the last time I played. My guess is that something changed inside the file that is messing with DADA. I'll do some debugging.

**Comment by jceddy** [comment]
Yeah, they changed some of the names of things in the log to numeric codes and other slight format changes, throwing it off. Working on a fix now.

**Comment by jceddy** [comment]
I've figured out the fix for part of it (wildcard/vault progress inventory), but so far have not figured out what they changed with the player card/deck inventories. Heading to Google to find what I can find...usually this kind of thing will affect other trackers (with larger dev teams) as well, so I can find some information.

**Comment by jceddy** [comment]
Looks like their latest round of log file changes broke this stuff for ALL trackers. I am talking to the owner of MTGArena.pro about creating a mod for the game to get this information. Unfortunately that kind of solution will take a *long* time to implement.

**Comment by kylejonmoon** [comment]
I don't know whether to continue on this thread or start a new one.  Now the program seems to recognize that I have enabled detailed logging, but it now says "Unhandled Exception - Sending Data to Server".

**Comment by jceddy** [comment]
I'll take another look today, it might be that they fixed something with the log files, but that there is still a change breaking it.

Unfortunately I am in the middle of setting up a new PC, so things are going a little slow as I get all the tools I use installed.

**Comment by jceddy** [comment]
Looks like adding the City's Blessing broke something, due to it showing up as a "card" with no type. Need to add code to ignore cards with no type line.

Not sure if they fixed the other issue yet, will figure that out once I fix this one.

**Edit**: They have not fixed it yet.

**Comment by jceddy** [comment]
I just pushed a new version 1.0.9.2

Anyone want to give it a test to see if it works for them now?

**Comment by jceddy** [comment]
should be fixed with latest update
