### ISSUE TITLE
Unhandled Exception - Sending data to server 

### ISSUE THREAD

**Issue by DallaraAero** [jceddy/DailyArenaDeckAdvisor#266]
I downloaded version 1.0.9.1, tried to open it, the message "loading database card" appears but the loading bar does not advance, a few moments later the message Unhandled Exception.
I've already tried deleting the .json in the directory, it doesn't work.

**Comment by jceddy** [comment]
So, there is a bug causing a crash when loading the card database, related to the addition of City's Blessing. I have a fix for it that hasn't been published yet. The larger issue is that their last major change removed a bunch of information from the detailed logs that DADA uses, and is basically nonfunctional without.

I have been working with some people to figure out a solution, as this affects *all* similar software, mtgarena.pro, etc., as well. Unfortunately it seems at this time that any solution is going to require a pretty complex change involving code injection or something, and will take a while to implement.

**Comment by jceddy** [comment]
Should be fixed in the new version 1.0.9.2.
