### ISSUE TITLE
Replacement suggestion for standard deck is non-standard

### ISSUE THREAD

**Issue by russelhampton05** [jceddy/DailyArenaDeckAdvisor#27]
Currently Llanowar elves is being recommended as a trade in for cards not in the collection while the rotation is set to standard. Llanowar elves is currently not in standard. I haven't noticed any other card specifically showing up that isn't in standard while the rotation selection is set to standard.

**Comment by jceddy** [comment]
Do you have it set to Rotation Proof.

There is a slight issue that it's treating rotation as the paper rotation time instead of the Arena rotation time, bit if you set it to Rotation Proof is should work correctly.

**Comment by russelhampton05** [comment]
Setting it to rotation proof did the trick. That makes sense - they've been dropping the cards early for Arena.

**Comment by jceddy** [comment]
👍 - closing issue
