### ISSUE TITLE
Importing decks are not always added to DADA

### ISSUE THREAD

**Issue by ghost** [jceddy/DailyArenaDeckAdvisor#30]
I have some decks I would like to analyse with the tool, but I have only been able to import 1 deck to the game and the tool. (maybe it has something to do with it having a sideboard?)

A decks directory with filename as deck name and arena export as body would make it very easy to manage them. you don't want your decks hardcoded forever do you? I would like to rename them and add my own decks to the list please.

**Comment by jceddy** [comment]
It shows decks in your collection that you are missing cards for.

Are the missing decks Historic by any chance? As I was writing this response I realized I never tested that functionality with Historic decks.

**Comment by ghost** [comment]
Yes, I just noticed they are.
A lot of the decks that didn't show up were decks imported from the mtga fandom site(npe decks I hadn't earned yet). I just tried one from the mtga.pro and its not showing either. But yes they are Historic, and I get an illegal deck warning when I switch it to standard after that they still aren't in the tool, and I have no idea what cards are illegal.

Still looking for more decks to be made aware of. The only deck I could play with just a few replacements was your R deck.

**Comment by ghost** [comment]
![DADA](https://user-images.githubusercontent.com/28419558/66263183-fe1d3500-e7b3-11e9-92da-7f4bd2195533.PNG)

This deck disappears from the list if I remove that card from the sideboard.

**Comment by jceddy** [comment]
Does it move to the Arena Standard list? The program uses the existence of
a sideboard to guess at whether it's a Standard (bo3) deck or an Arena
Standard (bo1) deck.

**Comment by ghost** [comment]
These decks show up in game under standard decks, and in your tool only in standard, not arena standard. (Only with a card in sideboard)

I have a deck where I am only missing 4 Gates and it is not showing up even with the sideboard card.

**Comment by jceddy** [comment]
If you could attach the output_log.txt (from c:\Users\\{username}\AppData\LocalLow\Wizards of the Coast\MTGA) here along with the names of the decks that aren't showing up, I could take a look and try to see what's going on and why.

**Comment by ghost** [comment]
[output_log.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3693899/output_log.txt)

Can you create your .json files to spoof your collection is very low like mine to test what I have found? (or even an empty collection)

I especially think its weird the deck that could easily be played if it would replace 4 gates doesn't show up unless I add another card I don't have.
Edit: In fact the tool says I have the 4 gates and recommends me to replace the opt (I don't have) with unsummon

**Comment by jceddy** [comment]
Your collection is taken from the same log file, I should see exactly what you see.

**Comment by jceddy** [comment]
Okay, so the decks I see showing up from your collection are as follows...

Standard:
Boros Legion - You have enough wildcards to craft it.
Chandra's Blaze - You have enough wildcards to craft it.

What is the name of the gates deck that is causing issues for you?

**Comment by jceddy** [comment]
Is it "Tolorian Tactics"?

**Comment by jceddy** [comment]
I found an issue when going through your log where I wasn't handling some cases properly when you do a lot of updating/deleting/creating decks in the same session.

This is fixed by changeset b3f6059, and I will be pushing a change for this sometime later today.

I'm closing the issue for now, but feel free to re-open it or open a new one if you're still having problems with it tomorrow.

**Comment by jceddy** [comment]
FYI: The update is available now...please let me know if you still have issues with it.

**Comment by ghost** [comment]
There are still a couple issues let me make a guide to reproducing them. 
Simic Combine 2 is the deck we will be looking at. In this deck i have added a second copy of Opt that I do not own. And I do not own the 4 simic guardgate required.
-EX1: The deck is not listed in the tool with no card in the sideboard. (It is missing opt and guildgates)
-EX2: With a card in the sideboard it appears in the tool and you can see the deck was always missing the Opt copy but the guildgates are listed as green, and they are not in my collection.

EX1 - There is no Simic combine 2 listed. without a card in the sideboard. 
[output_log.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3698502/output_log.txt)

EX1 - Working as intended for the Opt card, And is wrong in saying I own Simic Guildgates.
[output_log.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3698529/output_log.txt)

**Comment by ghost** [comment]
I think adding a toggle to display usable decks might be useful for more than debugging.
Also: you cannot re-open your own issues if a repo collaborator closed them.

**Comment by jceddy** [comment]
When I run your first output_log.txt, I see Simic Combine 2 listed under Arena Standard (which is where a deck without a sideboard will generally show up), with a replacement shown for the Opt.

![issue_30_01](https://user-images.githubusercontent.com/1302263/66331630-99b7be00-e8f8-11e9-870c-cd0e92fa32c2.png)

When I run the second output_log.txt, I see Simic Combine 2 listed under Standard (which is where a deck with a sideboard will generally show up), with a replacement shown for the Opt.

![issue_30_02](https://user-images.githubusercontent.com/1302263/66331802-f74c0a80-e8f8-11e9-9f6b-192e7b28a55a.png)

Simic Guildgate is in Arena under a few different versions with the following Arena Ids:
69405 (Ravnica Allegiance #257)
69406 (Ravnica Allegiance #258)
69725 (War of the Spark #274)

Digging into the collection info from your log file, I see:
0 copies of 69405
4 copies of 69406
0 copies of 69725

![issue_30_03](https://user-images.githubusercontent.com/1302263/66332291-03849780-e8fa-11e9-9edd-fed1987c87e2.png)

So you *do* own 4 copies of Simic Guildgate, at least according to your log file. My guess is that you imported the deck with a different version of Simic Guildgate and the Arena deck builder is doing a crap job of identifying that you own copies of a different version.

You can verify this in two ways:
1) Remove Simic Guildgate from the deck in Arena's deck builder, search for Simic Guildgate in the deck builder and add in the four copies it shows you.
2) Export the deck from DADA and re-import it to Arena. DADA is smart enough to pick any version of the card you own, regardless of the version it was imported to Arena with.

I'll re-open the issue for you. Please let me know whether either of these work for you.

**Comment by jceddy** [comment]
Also, if this is what turns out to be the issue (Arena's deck builder ignoring your alternate versions), you might consider opening an issue with WotC over it. :)

**Comment by ghost** [comment]
Okay I see that I do own the gates but they are a different card art (ids).

Angelic life steal is a deck where I am missing Serra's Guardian and the 50 plains cards in it are of card art I do not own. And i do not see it in the tool's standard/arena lists.
[output_log.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3698649/output_log.txt)

**Comment by jceddy** [comment]
Angelic Lifegain is not showing up because you own all of the cards. The only decks from your collection that DADA shows are ones that you don't own all of the cards for.  
  
If it's not showing up but somehow Arena is telling you it's in incomplete deck, that's a pretty good sign that it's Arena's deck building not being smart enough to tell that you own different versions of some card in the deck.

**Comment by ghost** [comment]
Okay I understand perhaps the wizards are just trying to preserve the cards original art for some reason? Yeah that's on them. I do not know my cards well enough yet to see I did own them :) I remember back when i would shuffle through all of the cards I owned to learn them out of boredom :)

I guess if you get bored you could show the equal cards to swap out. And show what decks would be able to be played with these direct replacements, While I have you here, I really like this app as is and can't wait to see what you add to it in the future.
