### ISSUE TITLE
Add legend or headings for left side list

### ISSUE THREAD

**Issue by SabreCat** [jceddy/DailyArenaDeckAdvisor#32]
Recent updates have multiplied the number of different text decorations used in the left side list. There's orange bold, yellow highlighted with dashed outline, italic green bold, blue bold, and black regular text. The meanings of some can be discerned by experimentation, others not so much. Would it be possible to add a legend somewhere to explain what they all mean? Or maybe use noninteractive headings in the list to separate out the sections rather than colors? Either approach would be great for UX and accessibility!

**Comment by jceddy** [comment]
This was on the separate list that I keep in my head already. :) (You or someone else asked for this on reddit, I think, a while back.)

I do have an explanation of the meanings of the different text decorations in the user guide (https://mtgazone.com/deck-advisor/). I made some changes to make it easier for folks with color blindness, but yeah, I think separating out the headings seems like the way to go.

I may change the title of this once I decide what change is actually going to be made to reflect what we ultimately decide on.

**Comment by SabreCat** [comment]
Ha, yeah, that was me, but I've since deactivated my Reddit account, so I thought I'd get my feedback in somewhere I could still keep track of it. Thanks for considering it!

**Comment by jceddy** [comment]
Thanks for sticking it here before I forgot about it. :)

This is by far the most reliable place to ensure the issue actually gets implemented or at least thought about before being dismissed.

**Comment by jceddy** [comment]
Pinning this. Going to try to work on it this week.

It's probably something that will only work under the default deck order sort.

**Comment by jceddy** [comment]
Tab headers added in release 1.0.5.5
