### ISSUE TITLE
Getting stuck on 'Computing Deck Suggestions'

### ISSUE THREAD

**Issue by Sephirah6075** [jceddy/DailyArenaDeckAdvisor#34]
Program updated and seems to work fine until it begins computing deck suggestions and then just stays there half-way through on the progress bar.
[log2019101211.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3720911/log2019101211.txt)

**Comment by jceddy** [comment]
Is there any chance you can include your output_log.txt file from C:\Users\\{your user}\AppData\LocalLow\Wizards of the Coast\MTGA

I can drop this into my machine's location and run in debug mode to replication the error locally (it's not happening for my collection).

**Comment by Sephirah6075** [comment]
Yes as soon I can I will post that log file

**Comment by riselka** [comment]
same for me, here is that log you asked for:
[output_log.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3725870/output_log.txt)

**Comment by jceddy** [comment]
The issue was apparently with one of my deck sources adding a trailing space to the name "Merfolk Scretkeeper". I've added code to handle this and put up a new version (1.0.4.2).

Please let me know whether this fixes the issue for you.

**Comment by riselka** [comment]
that fixed it, thanking you.

**Comment by jceddy** [comment]
Thanks for letting me know.

Closing the issue.
