### ISSUE TITLE
Getting stuck on 'Processing collection from log'

### ISSUE THREAD

**Issue by JimmiV** [jceddy/DailyArenaDeckAdvisor#35]
[firstChanceExceptions2019101314_001.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3721742/firstChanceExceptions2019101314_001.txt)

![Cattura](https://user-images.githubusercontent.com/5228876/66715905-0a634c80-edc9-11e9-8e7b-73da1a050a16.PNG)

**Comment by jceddy** [comment]
Could you also attach your arena log here?

It's output_log.txt from c:\Users\\{your user}\AppData\LocalLow\Wizards of the Coast\MTGA

**Comment by JimmiV** [comment]
Sure

Inviato da Posta per Windows 10

Da: jceddy
Inviato: domenica 13 ottobre 2019 19:24
A: jceddy/DailyArenaDeckAdvisor
Cc: Emiliano; Author
Oggetto: Re: [jceddy/DailyArenaDeckAdvisor] Getting stuck on 'Processingcollection from log' (#35)

Could you also attach your arena log here?
It's output_log.txt from c:\Users\{your user}\AppData\LocalLow\Wizards of the Coast\MTGA

**Comment by jceddy** [comment]
I put up a new version of DADA (1.0.4.2) this morning that fixes some bugs.

Please try again today and let me know if it fixes your issue.

**Comment by JimmiV** [comment]
I ran it yesterday and it worked.

In any case, thank you for your work

Ciao,
Emiliano

Inviato da Posta per Windows 10

Da: jceddy
Inviato: martedì 15 ottobre 2019 15:31
A: jceddy/DailyArenaDeckAdvisor
Cc: Emiliano; Author
Oggetto: Re: [jceddy/DailyArenaDeckAdvisor] Getting stuck on 'Processingcollection from log' (#35)

I put up a new version of DADA (1.0.4.2) this morning that fixes some bugs.
Please try again today and let me know if it fixes your issue.

**Comment by jceddy** [comment]
Thanks.

Closing the issue.
