### ISSUE TITLE
Stuck at loading card database

### ISSUE THREAD

**Issue by csokolo25** [jceddy/DailyArenaDeckAdvisor#36]
I downloaded 1.0.4.4. and I cannot get it to progress beyond loading card database. I have reinstalled MTG Arena, toggled the detailed logs, and reinstalled DADA, but nothing seems to fix the issue. I saw the thread from early September, but it only had things I already tried. Log files are attached. In attempting to resolve the issue I was perusing the troubleshooting section below the program download and did notice that the output_log under PlayerInventory.GetPlayerCardsV3 doesn't look like the example, but I don't know enough about the logs to know if what it shows is indicative of a problem. I have included that log as well. Hope you can help, love this program!

[output_log.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3748353/output_log.txt)

[firstChanceExceptions2019102015.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3748336/firstChanceExceptions2019102015.txt)
[firstChanceExceptions2019102016.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3748337/firstChanceExceptions2019102016.txt)
[log2019092620.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3748338/log2019092620.txt)
[log2019093020.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3748339/log2019093020.txt)
[log2019093023.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3748340/log2019093023.txt)
[log2019102015.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3748341/log2019102015.txt)
[log2019102016.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3748342/log2019102016.txt)
[updater.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3748343/updater.txt)

**Comment by jceddy** [comment]
It looks like the card database file on the server is empty somehow. Looking into it.

**Comment by jceddy** [comment]
I think I fixed it...can you try it again?

**Comment by csokolo25** [comment]
It works! Thank you!
