### ISSUE TITLE
hangup on loading deck archetypes

### ISSUE THREAD

**Issue by vtwo** [jceddy/DailyArenaDeckAdvisor#37]
everything was working until i selected historic bo1 from the dropdown menu in the top right corner. reinstalling doesn't fix it. is there anything i can do?

[log2019102111.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3749908/log2019102111.txt)
[firstChanceExceptions2019102111.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3749909/firstChanceExceptions2019102111.txt)

**Comment by jceddy** [comment]
Try deleting the state.json file in c:\Users\\{your user}\AppData\LocalLow\DailyArena\DailyArenaDeckAdvisor

Also if you could attach the output_log.txt file from c:\Users\\{your user}\AppData\LocalLow\Wizards of the Coast\MTGA it might be helpful for me to see what's causing it.

**Comment by vtwo** [comment]
deleting the state.json did the trick (so it loads into standard) but selecting the historic bo1 gives the same hang on archetypes. (the output_log.txt is 13mb btw)
[output_log.txt](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3750316/output_log.txt)

**Comment by jceddy** [comment]
This should be working now...can you give it a try to verify?

**Comment by jceddy** [comment]
Closing the issue, please comment back here if it's still not working for you.
