### ISSUE TITLE
Documentation assist / request

### ISSUE THREAD

**Issue by ghost** [jceddy/DailyArenaDeckAdvisor#4]
J.

I really enjoy your app and use it quite a bit to keep track of meta decks and which ones I can play. I'd love to contribute to the project. I don't write a lot of code but I do write a lot of Wiki entries for my DevOps / TechOps teams at my RL job.

If you'd like assistance with that, please let me know and I'd be happy to start working on documentation / wiki entries for DADA.

Mark Steele
msteele999 'at' gmail 'dot' com

**Comment by jceddy** [comment]
That would be wonderful. :)

**Comment by ghost** [comment]
Perfect,

If you have an initial writeup or reddit post please feel free to send it
over - I'll get it formatted for wiki and get it started.

Mark

**Comment by jceddy** [comment]
All I have currently are the four blog posts I created so far:

https://www.dailyarena.net/2019/08/02/mtga-deck-suggester/
https://www.dailyarena.net/2019/08/08/daily-arena-deck-advisor-v-1-0-1-1/
https://www.dailyarena.net/2019/08/16/daily-arena-deck-advisor-v-1-0-2-1/
https://www.dailyarena.net/2019/08/23/daily-arena-deck-advisor-v-1-0-2-6/

**Comment by ghost** [comment]
Excellent - I'll get right on it

**Comment by ghost** [comment]
J,

Do you think you want to have a link on the app that will open up the 'help' or 'FAQ' page? I'm thinking about what format the file should be- html5, xml, markup - or multiple.

**Comment by jceddy** [comment]
I might just have a link that points to the Wiki here and then folks could go from there.

I'm not sure what the Wiki here supports, probably just some mix of markdown and html.

**Comment by ghost** [comment]
Ok. I don't seem to have access to the wiki at the moment. Not sure if
that's something you have to change.

**Comment by jceddy** [comment]
Can you try again?

**Comment by ghost** [comment]
I have access now!

**Comment by ghost** [comment]
I've started fleshing out the wiki with sections that somewhat replicate
your blog postings. I am adding a section for the user manual and will be
adding screen shots.

In the other sections I simply copied the URL for your images and posted
those in the wiki and that worked well. In the case where I need to ADD
images, I'm trying to figure out where would be the best place to put them.
Do you have an ftp or web server location where I could put the images and
then reference them by URL? If not, we could probably setup either a drop
box, google drive or other location to put them. I think your images are
currently hosted with your blog provider based on the URL's.

I wonder if there is a place on the git repositiory for the project where I
could store images ....

**Comment by jceddy** [comment]
I created an FTP account that you can use to upload images an "external_images" folder on dailyarena.net.

Is there any chance you can shoot an email to dailyarena@dailyarena.net to get the login credentials? (I don't really want to post them here and then get some bot spamming images to it, even though I put a 20GB quota on for now.)

**Comment by ghost** [comment]
Updated Wiki:

- added 1.0.3.1 page
- removed 'User Manual' page and references - all that is covered in the release notes sections

**Comment by jceddy** [comment]
I added a new User Guide page to the wiki (https://github.com/jceddy/DailyArenaDeckAdvisor/wiki/User-Guide). Take a look when you get a chance and let me know if you see any issues.

**Comment by ghost** [comment]
Will do.

**Comment by ghost** [comment]
Looks great - looks like you don't need me anymore :-( LOL

**Comment by jceddy** [comment]
Imma close this issue so it's not showing up for me anymore. If you want to keep adding update pages, though, that would be great. :)
