### ISSUE TITLE
Allow deck to be imported for suggested replacement

### ISSUE THREAD

**Issue by frankcalise** [jceddy/DailyArenaDeckAdvisor#67]
Sometimes after I get beat by a deck I save the cards that were in the match to craft it later. However sometimes I don't have all of the cards if they're too rare etc, so it would be nice to get the advisors replacement check for this list.

I'd be open to working on a pull request if you have thoughts on how this could be implemented if it's a feature you'd like to include in the application.

**Comment by jceddy** [comment]
You can actually already do this. If you import a (incomplete) deck into Arena, it will show up in the deck advisor deck list for the deck's format in a "Player Decks" section.

**Comment by frankcalise** [comment]
Oh cool thanks, I didn't see the Player Decks section since I didn't have it on Arena Standard.

**Comment by jceddy** [comment]
![Deck List Image](https://www.dailyarena.net/wp-content/uploads/2019/11/advisor_25.png)

I also featured this in a short tutorial on Friday: 
https://www.dailyarena.net/2019/11/01/daily-arena-deck-advisor-v-1-0-5-6/

Oh you closed it while I was typing...well, take a look anyway if you're interested! :)
