### ISSUE TITLE
Text-Based Card Filter

### ISSUE THREAD

**Issue by jceddy** [jceddy/DailyArenaDeckAdvisor#72]
Add a TextBox to the filter bar that will filter for decks/cards that contain the text entered.
It should probably be a full-text search that includes the card's rules text (at least).
First version will probably only handle card names (not full rules text) for languages other than English, but eventually we should be able to support the full text search for other languages, as well.

**Comment by jceddy** [comment]
This is going to just be the card names for the initial implementation. Getting the full rules text is a little tougher than I thought at first.

**Comment by jceddy** [comment]
I'll make it case-invariant, culture-invariant, and have a way to use regular expressions.

**Comment by frankcalise** [comment]
Card names to start is more than fine

**Comment by jceddy** [comment]
Version 1.0.5.9 was pushed this morning, and contains this functionality.
Closing.
