### ISSUE TITLE
Banned cards?

### ISSUE THREAD

**Issue by mjv39474** [jceddy/DailyArenaDeckAdvisor#74]
Looks like field of the dead still shows up in decks. Since it's banned perhaps those decks should no longer show up?

**Comment by jceddy** [comment]
Good point. I would be nice if MTGATool would hide those decks, but I can probably figure out a way to add some general-purpose functionality for that.

**Comment by jceddy** [comment]
Commit https://github.com/jceddy/DailyArenaDeckAdvisor/commit/770e87d399baf2ec88bfc63708b2b64271d5315c added this functionality.

It will be included in the next release.

**Comment by mjv39474** [comment]
Nice!

**Comment by jceddy** [comment]
Version 1.0.6.0 was pushed this morning, which contains this functionality.
Closing.

**Comment by kaznovac** [comment]
@jceddy hi, there seem to be bug with this feature (or ban list has to be updated) i still see a lot of decks with oko thief of crowns, once upon a time, etc...

**Comment by jceddy** [comment]
Hmm...the source that my bannings info is coming from still only contains Field of the Dead. I'll look into it today.

This is one of the drawbacks of relying on external sources for data...I would hope that the sites the deck information is coming from would remove illegal decks. :P

**Comment by jceddy** [comment]
D'oh...I found a typo in the daily update code on the server side that is keeping banning info from getting updated correctly.

Also, I don't have a source yet for "suspension" info in historic, so I'm not sure what to do about that, ATM.

**Comment by jceddy** [comment]
Alright, I fixed the typo and re-ran the daily update script...the other three bannings were picked up on the server side and appear to be trickling down to the client correctly.

Can you verify it's working for you again?

**Comment by mjv39474** [comment]
It seems to work fine for me now. I meant to report this, but got busy 
with other things, so I'm glad someone else picked this up.

As an aside, it might be worthwhile to show the sources for some of the 
data that you're getting. I was going to actually pull the code and 
compile it to figure that out, but as I said, I got busy :-).

**Comment by jceddy** [comment]
Yeah, I might add some links:

The deck info comes from mtggoldfish and mtgarena.pro

Other info comes from mtgarenatool, whatsinstandard.com, and scryfall

**Comment by jceddy** [comment]
All of the data is compiled on my web server by back-end processes that aren't part of the github project, though, so everything you'd see would be pointing back to clans.dailyarena.net

**Comment by kaznovac** [comment]
@jceddy i can confirm the fix, great job :)
