### ISSUE TITLE
Question: how to delete yellow decks ?

### ISSUE THREAD

**Issue by ridcullykira** [jceddy/DailyArenaDeckAdvisor#89]
i want to delete some yellow decks and cant find any answers.

my brother and I share the same computer sometimes when he is visiting me. 
after he showed me somthing on his account with some decks he made, the decks show up in the deck advisor. 
i tried to reset the advisor, but they are still showning. 

is there a simple way to clean this inside the programm? or do i need to delete and re-install ?

greetings
![yellow decks](https://user-images.githubusercontent.com/7340705/69194218-e3ffa200-0b28-11ea-8363-08c21647409b.png)
ridcully

**Comment by jceddy** [comment]
I've seen this issue on my machine (i use 2 accounts). I have been planning to add some code to keep it from happening, but haven't done it yet (maybe will prioritize now that I know it's affecting others).

Workarounds: if you exit Arena completely and re-run it that will usually purge the log and you won't see decks from the other account anymore

There is also a filter to hide decks from the player inventory, I believe.

**Comment by jceddy** [comment]
Checked in commit 2c88553 this morning, which fixes this...it will be in the next release.

**Comment by jceddy** [comment]
Pushed version 1.0.6.3, which should fix this.
Closing.
